name = "SyntheticLikelihood"
uuid = "dd14a069-f616-42ae-bdb8-5921107d30e5"
authors = ["Daniel Ward"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[compat]
Distributions = "0.24"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
